[profile.default]
allow_internal_expect_revert = true
src = "src"
out = "out"
libs = ["lib"]

optimizer = true
via-ir = false
optimizer-runs = 10_000_000

fs_permissions = [{ access = "read-write", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
